README.md
main.tf
outputs.tf
variables.tf

Add boolean variable to enable system assigned managed identity if needed.

feat: enable system assigned managed identity

---

README.md
examples/basic/main.tf
main.tf
outputs.tf
variables.tf

BREAKING CHANGE: remove variable `service_plan_id`
BREAKING CHANGE: add variable `service_plan_name`
Closes #34

feat!: create service plan

---

README.md
examples/basic/README.md
examples/basic/main.tf
examples/container-app/README.md
examples/container-app/main.tf
examples/container-app/variables.tf
main.tf
test/container_app_example_test.go
variables.tf

Enable deployment of non-dockerized application.
BREAKING CHANGE: rename variable `managed_identity_client_id` to `acr_managed_identity_client_id`
BREAKING CHANGE: remove variable `managed_identity_id`
BREAKING CHANGE: add variable `managed_identity_ids`
Closes #31

feat!: deploy non-docker apps

---

README.md
examples/container-app/main.tf
main.tf
variables.tf

feat: disable authentication settings

---

examples/container-app/main.tf
examples/linux-app/main.tf
examples/windows-app/main.tf
modules/linux-app/main.tf
modules/windows-app/main.tf

Prevent app settings configured outside of Terraform from being removed.

fix: ignore changes to app settings

---

main.tf

Forgot to pass value from main module to submodule.

fix: enable websockets when calling main module

---

examples/active-directory-auth/main.tf
examples/active-directory-auth/variables.tf
examples/container-app/main.tf
examples/linux-app/main.tf
examples/windows-app/main.tf
main.tf
modules/app/main.tf
modules/app/outputs.tf
modules/app/variables.tf
outputs.tf
test/active_directory_auth_example_test.go
variables.tf

feat!: create multiple active directory auth settings

---

examples/container-app/main.tf
main.tf
modules/app/main.tf
modules/app/outputs.tf
modules/app/variables.tf
variables.tf

Update variable names and types to follow baseline best practices.

refactor!: update variables according to baseline

---

examples/active-directory-auth/main.tf
main.tf
modules/app/main.tf
modules/app/variables.tf
variables.tf

feat!: set app settings

---

examples/active-directory-auth/main.tf
main.tf
modules/app/main.tf
modules/app/variables.tf
variables.tf

revert: set app settings

---

examples/container-app/README.md
examples/container-app/main.tf
examples/linux-app/README.md
examples/linux-app/main.tf
examples/windows-app/README.md
examples/windows-app/main.tf

- Update Log Analytics module call to use latest version in all examples.
- Update ACR module call to use latest version for `container-app`-example.
- Update example `README.md`.
Closes #64
Closes #71

chore: update examples

---

examples/active-directory-auth/main.tf
examples/container-app/main.tf
examples/linux-app/main.tf
examples/windows-app/main.tf
main.tf
modules/app/main.tf
modules/app/variables.tf
variables.tf
versions.tf

feat: set log analytics destination type and update min. provider version

---

main.tf
variables.tf

Forgot to add variable to root module in #87.

fix: set diagnostic setting enabled log categories

---

main.tf
variables.tf

Default value set to `"Error"`, same as in Azure Portal.

feat: set application log level

---

main.tf
variables.tf

Add variable for enabling vnet_route_all_enabled feature on both linux and windows web app

feat: add vnet route all enabled variable

---

main.tf
variables.tf

BREAKING CHANGE: change variable `custom_hostnames` type

feat!: specify custom hostname binding type

---

examples/container-app/main.tf
main.tf
variables.tf

BREAKING CHANGE: remove variable `identity`, add variables `system_assigned_identity_enabled` and `identity_ids`.

refactor!: simplify identity configuration

---

main.tf

Similar to equinor/terraform-azurerm-function-app#38.

fix: user-assigned identities not being assigned

---

variables.tf

fix: remove unused variable

---

main.tf
variables.tf

feat: set client affinity and FTPS state

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.gitignore
README.md
examples/active-directory-auth/main.tf
examples/active-directory-auth/variables.tf
examples/container-app/main.tf
examples/container-app/variables.tf
examples/linux-app/main.tf
examples/linux-app/variables.tf
examples/vnet-integration/main.tf
examples/vnet-integration/variables.tf
examples/windows-app/main.tf
examples/windows-app/variables.tf

Document how to develop and test this module.

docs: development and testing

---

main.tf

Remove code duplication by adding locals for all reused values.

refactor: add locals for reused variables

---

main.tf
variables.tf

Added a new variable for ip_restriction.

feat: add variable `ip_restrictions`

---

main.tf
variables.tf

Added a new variable for app_settings.

feat: add variable `app_settings`

---

main.tf
variables.tf

Added a new variable for active_directory_tenant_auth_endpoint.

feat: add variable `active_directory_tenant_auth_endpoint`

---

main.tf
variables.tf

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

feat: add variable `diagnostic_setting_name`

---

CODE_OF_CONDUCT.md

docs: create code_of_conduct.md

---

CODE_OF_CONDUCT.md

docs: update code_of_conduct.md

---

outputs.tf

added default hostname to outputs

feat: added default hostname to outputs

---

main.tf
variables.tf

Added the possibility to define an application stack to define a docker container to be used by the app.

feat: add application stack variable

---

main.tf
variables.tf

Added possibility to open inobund internet traffic based on Service Tag

feat: add service tag possibility

---

outputs.tf
variables.tf

chore: update variable and output descriptions

---

main.tf
variables.tf

feat: add custom login parameters variable

---

.github/CODEOWNERS

chore(docs): Update CODEOWNERS

---

README.md

docs: add features section to README

---

main.tf
variables.tf

feat: configure connection strings

---

main.tf

fix: configuring connection strings throws error

---

locals.tf
main.tf

Add a separate file `locals.tf` for local variable definitions (as recommended in the [official Terraform style guide](https://developer.hashicorp.com/terraform/language/style#file-names)).

refactor: add separate file for locals

---

examples/storage-mount/README.md
examples/storage-mount/main.tf
examples/storage-mount/variables.tf
main.tf
variables.tf

feat: mount Storage accounts

---

main.tf
variables.tf

added zip file deploy attributes to the webapp.
This attribute allow quick deployment of local package

feat: deploy local ZIP-packaged application

---

main.tf

fix: ignore changes to hidden tags

---

outputs.tf

feat: add site_credential outputs

---

main.tf
variables.tf

Added new variabel for basic authentication publishing

feat: add variable for basic authentication for publishing

---

main.tf
variables.tf

feat: configure HTTP/2 protocol

---

main.tf
variables.tf

feat: configure 32-bit worker

---

main.tf
variables.tf

Fixed variable for `virtual_applications` where we won't have to add `virtual_directories` specifically as an empty list

fix: null default value for virtual directory

---

README.md

docs: clarify kind of Web App created by default

---

variables.tf

Clarify behaviour when the values of nullable variables are set to null.
Release-As: 15.13.3

docs: update descriptions for Microsoft Entra variables

---

main.tf
variables.tf

feat: configure for sticky settings in web app
