equinor/terraform-azurerm-web-app

README.md
main.tf
test/fixture/main.tf
variables.tf

Automatically reference key vault secret for client secret instead of expecting user to construct key vault reference string.

Improve handling of client secret

---

README.md
main.tf
variables.tf

Allow user to pass in a list of custom hostnames to use for the Web App.
For each custom hostname in the list, create a custom hostname binding, a managed certificate, and a certificate binding.

feat: add custom hostnames

---

README.md
main.tf
outputs.tf
test/fixture/main.tf
variables.tf

BREAKING CHANGE:
Removed resource `azurerm_service_plan.this`. We do not always want to create a new service plan, sometimes we want to use a single service plan for multiple web apps. Thus, this should be created outside of the module instead.

feat!: remove service plan resource

---

README.md
main.tf
outputs.tf
test/fixture/main.tf
variables.tf

Reduce number of input variables required to setup Azure AD authentication.
BREAKING CHANGE: variable `app_service_settings` removed
BREAKING CHANGE: variable `azuread_client_id` renamed to `aad_client_id`
BREAKING CHANGE: variable `key_vault_name` removed
BREAKING CHANGE: variable `key_vault_secret_name` removed

feat!: simplify auth settings

---

README.md
examples/basic/README.md
examples/basic/main.tf
examples/container-app/README.md
examples/container-app/main.tf
main.tf
modules/linux-app/README.md
modules/linux-app/main.tf
modules/linux-app/outputs.tf
modules/linux-app/variables.tf
outputs.tf
variables.tf
versions.tf

Pass a map of apps to create on the service plan.
BREAKING CHANGE: remove variable `app_name`
BREAKING CHANGE: remove variable `auth_settings_enabled`
BREAKING CHANGE: remove variable `aad_client_id`
BREAKING CHANGE: remove variable `aad_client_secret_setting_name`
BREAKING CHANGE: remove variable `acr_managed_identity_client_id`
BREAKING CHANGE: remove variable `managed_identity_ids`
BREAKING CHANGE: remove variable `custom_hostnames`
BREAKING CHANGE: remove output `app_id`
BREAKING CHANGE: remove output `app_name`
BREAKING CHANGE: remove output `aad_client_secret_setting_name`
BREAKING CHANGE: remove output `identity_principal_id`
BREAKING CHANGE: remove output `identity_tenant_id`

feat!: create multiple apps

---

examples/container-app/main.tf
examples/linux-app/main.tf
examples/windows-app/main.tf

Set feature flag within the `features` block when configuring the provider to enable Terraform to delete resource groups still containing resources.

chore(examples): set feature flag in provider config

---

README.md
modules/linux-app/variables.tf
modules/windows-app/variables.tf
variables.tf

Update app inputs to not be nullable, so that if a value `null` is passed to one of these inputs, it will use the default value of the variable instead of `null`.

fix: make app inputs not nullable

---

modules/linux-app/README.md
modules/linux-app/outputs.tf
modules/linux-app/variables.tf
modules/windows-app/README.md
modules/windows-app/outputs.tf
modules/windows-app/variables.tf

Azure AD authentication already optional through use of `auth_settings_enabled` variable.
Simply update variable descriptions to be more clear instead.
Closes #49

refactor: update variable and output descriptions

---

README.md
modules/linux-app/README.md
modules/linux-app/main.tf
modules/linux-app/variables.tf
modules/windows-app/README.md
modules/windows-app/main.tf
modules/windows-app/variables.tf
variables.tf

Specify a managed identity that will be used to fetch app settings sourced from Key Vault.

feat: use managed identity for keyvault refs

---

modules/app/outputs.tf

Fix logic that would trow an error if trying to retrieve identity if it is not configured.

fix: output null if identity not configured

---

examples/active-directory-auth/main.tf
modules/app/variables.tf
variables.tf

Enabling auth settings (previously by default) while not configuring any auth settings providers makes the web app inaccessible.

fix: disable auth settings by default

---

modules/app/variables.tf
variables.tf

Identity requires the user to specify a type of either `SystemAssigned`, `UserAssigned` or both.
Set type to `SystemAssigned` by default to simplify usage.

refactor: set identity type to system-assigned by default

---

modules/app/main.tf
modules/app/versions.tf
versions.tf

The implementation of `auth_settings_v2` seems flaky at the moment (sometimes seems like it was configured correctly, however authenticating to web app redirects to a blank page).
Revert for now, consider re-implementing once AzureRM provider has been updated.

revert: migrate to auth settings v2

---

main.tf
variables.tf

Follow variable naming and type conventions.
BREAKING CHANGE: variable `custom_hostnames` renamed to
`custom_hostname_bindings` and type changed from `list` to `map`.

refactor!: follow variable best practices

---

main.tf

Azure automatically removes the `auth_settings` block when no actual auth settings (e.g. `active_directory`) are configured.
Add a check to only create the block when auth settings are to be configured.

fix: only configure auth settings when enabled

---

main.tf

If a Key Vault reference identity ID is specified, automatically assign it to the Web App.
This simplifies the configuration of the Key Vault reference identity, as its ID only has to be specified once.

feat: auto assign Key Vault reference identity ID

---

examples/active-directory-auth/main.tf
main.tf
variables.tf
versions.tf

Also simplify configuration of auth settings (see `active-directory-auth` example).
BREAKING CHANGE: remove variables `auth_settings_enabled` and `auth_settings_active_directory`, add variables `active_directory_client_id` and `active_directory_client_secret_setting_name`.

feat!: migrate to auth settings V2

---

main.tf
variables.tf

Automatically enable Managed Identity authentication to Container Registry if a value is provided for the `container_registry_managed_identity_client_id` variable.
Managed Identity authentication can still be manually enabled/disabled using the `container_registry_use_managed_identity` variable.

feat: auto use managed identity for container registry

---

main.tf
variables.tf
versions.tf

Allow managing app settings either in or outside of Terraform. Previously, we were only able to manage app settings outside of Terraform.

feat: manage app settings

---

examples/container-app/main.tf
main.tf
variables.tf
versions.tf

- Add properties `docker_registry_url`, `docker_registry_username` and `docker_registry_password` to variable `application_stack`.
- Add validation rule to variable `app_settings` to ensure Docker settings are configured using variable `application_stack` instead.
- Update `container-app` example to demonstrate configuration of Docker settings.

feat: configure Docker registry settings

---

variables.tf

Add validation rule to variable `app_settings` to prevent configuration of the following app settings:
- `WEBSITE_HTTPLOGGING_ENABLED`
- `WEBSITE_HTTPLOGGING_RETENTION_DAYS`
- `WEBSITE_HTTPLOGGING_CONTAINER_URL`
These app settings are set automatically by Terraform based on the values of 
the `azurerm_linux_web_app.this[0].logs[0].http_logs` and `azurerm_windows_web_app.this[0].logs[0].http_logs` block.

fix: prevent configuration of HTTP logging using app settings

---

main.tf
variables.tf

I added the `ip_restriction_default_action` and `scm_ip_restriction_default_action` variables to be able to block access to IP addresses that do not match any ip_restriction rule. In the current version, the value is set to its default value `allow` which makes ip_restrictions rules only able to block traffic, not restrict it.

feat: add ip restriction default value variables

---

versions.tf

v3.95 required to set `ip_restriction_default_action` and `scm_ip_restriction_default_action`: https://github.com/hashicorp/terraform-provider-azurerm/blob/main/CHANGELOG.md#3950-march-08-2024

fix: correct required provider version

---

main.tf
variables.tf

App settings `BUILD`, `BUILD_NUMBER` and `BUILD_ID` are commonly used for keeping track of which build is deployed to the Web App. Ignore changes to these settings to allow them to be configured from CI/CD pipelines.

fix: ignore changes to common build settings

---

variables.tf

Clarify which app settings should be configured using dedicated variables or outside of Terraform

fix: clarify app settings exceptions

---

variables.tf

fix: case-insensitive validation of `BUILD*` app settings

---

README.md
main.tf
variables.tf
versions.tf

Remove custom validation rule for variable `app_settings` that prevents configuration of build settings, and instead add a check block that throws a warning to notify users that any changes made to build settings outside of Terraform will be ignored.
Here's how the warning looks when trying to configure app setting `BUILD`:
This is because our logic to prevent configuration of build related app settings depends on the `ignore_changes` meta-argument. A limitation of this meta-argument is that it only accepts static values. That means that to support all case variations of the three relevant settings (`BUILD`, `BUILD_NUMBER` and `BUILD_ID`), we'd need...
`BUILD`: 2^5 = 32
`BUILD_NUMBER`: 2^11 = 2048
`BUILD_ID`: 2^7 = 128
32 + 2048 + 128 = **2208 static entries in `ignore_changes`** 🙃 
So …

fix: throw warning instead of error when trying to configure build related app settings

---

examples/linux-app/main.tf
examples/linux-app/variables.tf
main.tf
variables.tf

We used this module internally and made some changes which need to be compliant as per internal compliance policy.
Below are the changes -
**log_analytics_workspace_id** was mandate before now we have added a variable to handle it if this can be used or can be skip using the following  **logs_analytics_enable**.
We have added 2 more attributes to the webapp **client_certificate_mode & client_certificate_enabled** and we parameterized this attribute the **public_network_access_enabled**.
We have done a testing with these changes and it is working as expected.

feat: configure client certificate and public network access

---

variables.tf

Hidden tags are managed by Azure.
Changes to these tags are ignored anyway (#218).

fix: prevent configuration of hidden tags

---

main.tf
variables.tf

Created a variable for settings virtual app path mappings for windows web apps. Virtual Application doesn't exist for Linux web apps.
There is an issue when importing existing windows web apps with virtual application set it will try to delete a set virtual application.
Please contribute if this is the wrong way or I'm missing something.

feat: configure virtual applications

---

README.md
main.tf
versions.tf

A second attempt at implementing incremental updates of app settings.
First attempt at an implementation was in #246, however we experienced that app settings implicitly managed by Terraform (e.g. `DOCKER_REGISTRY_SERVER_URL`) were lost during updates. As a result, this change was reverted in 377f2c227926fe4f684849109b2da05cf19c8935.

fix: app settings implicitly managed by Terraform lost during update

---

locals.tf
main.tf
versions.tf

- Replace argument `metric` with `enabled_metric`.
- Bump minimum allowed Azure provider version. Version 4.31.0 is required to use the `enabled_metric` argument.

fix: argument `metric` for resource `azurerm_monitor_diagnostic_setting` has been deprecated

---

main.tf
variables.tf

Currently we deny all traffic to the Source Control Manager (SCM) by default. The only option to allow any traffic is to allow *all* traffic by setting the value of variable `scm_ip_restriction_default_action` to `"Allow"`.
Add variable `scm_ip_restrictions` that can be used to allow *specific* traffic instead of all traffic.

feat: add variable `scm_ip_restrictions`
